# Generated by Django 5.2.5 on 2025-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('published_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('raw_data', models.JSONField()),
            ],
            options={
                'ordering': ['-last_modified_date'],
            },
        ),
    ]
